version: '3.8'
services:

  db:
    container_name: foodgram_database
    image: postgres:13.0-alpine
    volumes:
      - db_volume:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    container_name: foodgram_backend
    image: newzealand/foodgram:latest
    restart: always
    volumes:
      - static_value:/app/static_backend/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  #frontend:
  #  container_name: foodgram_frontend
  #  image: newzealand/frontend:latest
  #  volumes:
  #    - frontend/:/app/result_build/
  #  depends_on:
  #    - backend

  frontend:
    container_name: foodgram_frontend
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend

  nginx:
    container_name: foodgram_nginx
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static_backend/
      - media_value:/var/html/media/
    depends_on:
      - backend
      - frontend

volumes:
  db_volume:
  static_value:
  media_value:
  
