# Generated by Django 2.2.19 on 2022-09-13 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20220913_1012'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserCart',
            new_name='Cart',
        ),
    ]
